services:
  redis:
    image: redis/redis-stack-server
    ports:
      - "6379:6379"

  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  phoenix:
    image: arizephoenix/phoenix:latest
    ports:
      - "6006:6006"
